<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>RacingGame</AssemblyName>
    <RootNamespace>RacingGame</RootNamespace>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <DefineConstants>$(DefineConstants);MONOGAME</DefineConstants>
    <TargetFramework>net8.0-windows</TargetFramework>
    <OutputPath>bin\MonoGameDX\$(Configuration)</OutputPath>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  
  <ItemGroup>
    <PackageReference Include="DigitalRiseModel.Gltf.MonoGame" Version="0.5.1" />
    <PackageReference Include="MonoGame.Framework.WindowsDX" Version="3.8.4" />
  </ItemGroup>

  <ItemGroup>
    <None Update="Assets\**\*.*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
</Project>
